### ISSUE TITLE
Publishing CLI & Restful API

### ISSUE THREAD

**Issue by Nevraeka** [customelements/www#210]
New Feature Idea:
A Restful API that allows adding, removing, updating, & read/search access to customelements.io

Because its not JS specific and it's a Restful API, this would be extremely an useful feature to add so other communities ( & even web development teams/groups) could easily create their own wrappers around the API to quickly create/manage their public components. 

One use case would be to build an NPM Module or Ruby Gem that would: 

* validate component integrity & compatibility locally
* Check if a similar component exists
* via cli - publish, unpublish, remove, add, search for, & view custom elements 
  
Also - Adding the capability to versioning component (via github tags or some other mechanism) might help compat & production usage but is a huge additional undertaking to start. 

Thoughts?

**Comment by zenorocha** [comment]
Hey guys,

It's been a while since this idea was proposed but I wanted to let you know that we thought about it and we'll probably provide a REST API for people to add their own elements. There still many many things to arrange but we'll keep you updated on that. In the meanwhile, here's a sneak peek: 

![screen shot 2015-02-27 at 10 13 41 am](https://cloud.githubusercontent.com/assets/398893/6413021/af58bd4a-be69-11e4-9119-88c6393a1640.png)

**Comment by obetomuniz** [comment]
:+1:  Nice!

**Comment by keppelen** [comment]
:+1:  ;)

**Comment by robdodson** [comment]
Cool!

On Fri, Feb 27, 2015 at 6:42 AM, Giovanni keppelen <notifications@github.com

**Comment by Nevraeka** [comment]
:+1:

**Comment by addyosmani** [comment]
:+1:

**Comment by zenorocha** [comment]
We decided to not publicize this API docs at this moment. There's constant changes being made and we'll be focusing our time on making the search experience better instead.
