### ISSUE TITLE
Add support for emoji

### ISSUE THREAD

**Issue by zenorocha** [customelements/www#499]
<img width="390" alt="screen shot 2015-08-07 at 9 00 13 am" src="https://cloud.githubusercontent.com/assets/398893/9140001/c158ec2a-3ce2-11e5-868f-be0253432e38.png">

**Comment by mkautzmann** [comment]
Let's do it!

To make it work we need to:

1) Parse the colon syntax used by GitHub and other fellows, but also need to support the unicode way.

2) We can load images or svgs instead of native emojis on devices that cannot show them.

To help us out we could use something like [emojify.js](https://github.com/Ranks/emojify.js).

I can explore a solution and submit a PR if you'd like to take on this approach.

**Comment by zenorocha** [comment]
Hey @mkautzmann,

That would be awesome!

**Comment by mkautzmann** [comment]
OK, I think I have a possible solution. Is it fine to target `master` in the PR? The [CONTRIBUTING](https://github.com/customelements/www/blob/master/CONTRIBUTING.md) guide does not specify that and there are a few possible branches...

**Comment by zenorocha** [comment]
Yep, master is alright.

**Comment by zenorocha** [comment]
Done! ;)
